---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - b3e65ac5c4b3715d136337f16cb4f230
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      no-undef:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "server/routes.js"
- "server/server.js"
